# .streamlit/secrets.toml

# Habilita OpenRouter e configura URL
enable_openrouter = true
OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions"

# Sua API Key
OPENROUTER_API_KEY = "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"

# Modelo padrão
MODEL = "nousresearch/deephermes-3-mistral-24b-preview:free"

# Segredos para a conta de serviço do Google Cloud
[gcp_service_account]
type = "service_account"
project_id = "medstudent-465922"
private_key_id = "e3cea2ee8aff82146de5257adf5a3dec81f33a68"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCRy7Szj2fitXhx\nbKfu/mzdLg5NIaGpDjqI352eIzM+LPsdpjaHpd11r2c8mQmaXyYWS9eztpIkdidu\n5hJYUSYPke1HLtlU5Im8Qea6dp5Hhiyqq4+IrPzFOrwbubLjf0eXtoR4Dtji765c\nv2MvAjDL3wtGsLF4QGTpgWFCR3E6jWMWIDuoSRf+dyBYZ5Gmv8zJljDm29SMZjKc\nxQQqUaDY6BxDbd7bLyhQt+bKaRxlRXeo3BVWMj+XndPIaM7IGtQKg6wc3q7qp6Ue\n5MRsguC/94y6JwZx+tN+XNSqm5c/NNnJykNqkuE2lhfmwtsmo9bpCR/9xm3ZT+oS\nQxJ0et2vAgMBAAECggEADABLV5yDs1MMybQP/smisceLayihjgZF0I6CWEoS0G4T\ncwADl8GSK+XMXF3x6cB7T3U0GZmls1VRLv0b9XkjO5Tfhe8tT0z1/tvN36Yepp88\n01pb7lGPB7fV/tJCZMeitQepJS4pBu/ZLSPz83f9XErNOtHAn2LC68BiqSSzBVwO\nOQh0BQAM89KkJutuA+AaZI89lOXo7+0Ix97ffSEcn1p5ydMJcQQUAZyvT6LoZYV5\nQBEexM64PlgFxZk+UDubX0IWICJABrM1t5g/bF6iC7oGW+J6ze6mV8T71pZMQtgk\n2iODD9ayBiS+nwQn7sSDwhN+51/MErCmxvPcneyTwQKBgQDMRKbFNNL8ioDY5hxP\nV0djx+LNl4R3LRzcH73a935ZfzUNvQoE8hobp5+QkwWnHckSh4wsDwazjL8buzC4\nNbPzeQuaPqX3r8bSJ5aNlK00XdzLsmm9FAtNeAyKnLg8Jcf2CWNdeamgWUaivEhc\nW/m9moGamUN3MoD2BJlCgR2ZHQKBgQC2uBoPsOU/VZxOld92OgwLJGxLcx1Bwvkz\nlRaA1KXEGfa0OJbR/7mShyX1tfRZrBBB8NwNMEIV3MuKvCaQ3t7MDv7WachWIAYS\nW8CH3Z8UzBUWS0ZFK+GnYYVktlgl5XWiuc3pc6zNmw8zLyfI70clxmcUQIIKZq3b\nBCx9fDqkOwKBgQCAcEpMhcKEeLI7r7TtTnvdCbpae4MXTI5w+qRuImCX9ZxuXwcF\nxRUVfnied1N+mQPtWr2QloIoM7+WuEUSDvJvjRT2j53b9/KUAcBwlaOy4bILgstp\n0EirFWkNXy2Y5EivM4f/Jpi58mivuqPlLxABYD1N8ECzmlXsW0fiwTzTIQKBgQCD\nqXVeCSGn2ZCgL+6tynYTMVO3qmNSl6PqP2vPuWsZO3xBsOU8vQCDTU9VFp/UXd/5\nJA3skvGLv2YLujgv++ifMc7/wYnSRZEaeXLqdA/FdKldPzCLd2tKqULtp1ctN4Lk\nlu6BYhEKtsjlIP2SFJk35xcvyKvrwsFUKFXGtlWrMQKBgB9WyHIWWhi3VhjbxJ11\nF/GQEORLcOH1dkfBP6iYpk0cY3Oe1bH12FIeZmrgJzPva/JLpOCfcgsexf8IqQr1\nHyeBTSBpZEzI7twJjQgkda2Ykst3tUdjjOelUB6vZ8kywa58HOTbTZdsqwklBxuE\nXWAZsxEdUbI0LiONr6wQGicH\n-----END PRIVATE KEY-----\n"
client_email = "medstudent@medstudent-465922.iam.gserviceaccount.com"
client_id = "107106136695412890592"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/medstudent%40medstudent-465922.iam.gserviceaccount.com"

# Segredos para a planilha
[gcs]
sheet_name = "medstudent"

# Segredos para a API do Gemini
[google_ai]
api_key = "AIzaSyCo6NHnZ8g9QVMiL2DnSPYYtQRWCT-7FeQ"

[connections.supabase]
SUPABASE_URL = "https://gupeyvxderpzflctfbxg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cGV5dnhkZXJwemZsY3RmYnhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTIwNzIsImV4cCI6MjA2ODk2ODA3Mn0.AavDJvloqg8ydJT3kAKOvPQ2Vc6nOZt7Lx5Hd_xfpKw"